FROM python:3.8
ADD ./producer/requirements.txt /
ADD ./producer/main.py /
ADD ./proj/ /proj/
RUN pip3 install -r requirements.txt
ENTRYPOINT celery -A main worker --concurrency=4 --loglevel=info -n producer_worker.%h
