version: '3.8'

services:

    proj:
      build: './proj'
      ports:
        - "5001:5001"
      depends_on:
        - rabbit

    rabbit:
        hostname: rabbit
        image: rabbitmq:management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - 15672:15672
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    addition:
        image: calc-addition
        build:
            context: .
            dockerfile: ./addition/Dockerfile
        links:
            - rabbit
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure

    subtraction:
      image: calc-subtraction
      build:
        context: .
        dockerfile: ./subtraction/Dockerfile
      links:
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    multiplication:
      image: calc-multiplication
      build:
        context: .
        dockerfile: ./multiplication/Dockerfile
      links:
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    division:
      image: calc-division
      build:
        context: .
        dockerfile: ./division/Dockerfile
      links:
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
